### ISSUE TITLE
Hunger Commands

### ISSUE THREAD

**Issue by nihal111** [Terasology/Hunger#10]
- There is a random "Temp testing command" called `temp` that should be removed.
- The `hungerCheck` command should have a DEBUG_PERMISSION
- The `hungerSet` and `hungerSetMax` command should have a CHEAT_PERMISSION

Look at https://github.com/MovingBlocks/Terasology/blob/develop/engine/src/main/java/org/terasology/logic/console/commands/CoreCommands.java for usage references.

**Comment by Cervator** [comment]
Closing as complete!
