### ISSUE TITLE
Hunger (and Thirst) shouldn't count down while a player is offline

### ISSUE THREAD

**Issue by Cervator** [Terasology/Hunger#13]
At present if you start a server with Hunger and/or Thirst active any player will have their stats slowly drain whether online or not - meaning if you stay offline a while then log in you're immediately starving and dying of thirst.

It would be better to only drain when the player is literally online - unless somebody *really* wants some hardcore survival. In that case maybe it can be an option that defaults to being off.

On a related topic since this affects Hunger and Thirst evenly we might want a central library module ("Sustenance" ?) that handles the logic and just has hooks for registering flavor modules like Hunger or Thirst that come with a bar and any unique logic. Then we could fix an issue like this in a single place. 

We've talked about that in the past somewhere but I can't recall where ...

Pinging @jellysnake for interest

**Comment by ktksan** [comment]
I looked into this issue and concluded that this is no longer an issue.
I followed the following steps:
I ran two instances of the game via IntelliJ (allowing parallel instances). Hosted a sever form one, joined from the other.
And after messing around a bit with the inspectionTool, I decided to test whether the hunger was in-fact decreasing when a player goes offline.
Following are the two screenshots to note the hunger bars of the two players.
![image](https://user-images.githubusercontent.com/50916693/76890640-ba277380-68ad-11ea-81ce-001804f6fe04.png)
![image](https://user-images.githubusercontent.com/50916693/76890846-17232980-68ae-11ea-9226-0797d855f15b.png)

Then I exited the server from the non-host instance.
![image](https://user-images.githubusercontent.com/50916693/76890950-3ae66f80-68ae-11ea-85be-28b220e22378.png)

Then after about 20 mins (after an episode of HIMYM) I rejoined the server from the non-host instance then I waited for about 5 mins to check if the hunger bar would drop in an abnormal way only to find it didn't. It resumed from its last known value whereas that of the host had dropped an appropriate amount.
![image](https://user-images.githubusercontent.com/50916693/76891273-b6e0b780-68ae-11ea-9e60-7b2c119af870.png)
![image](https://user-images.githubusercontent.com/50916693/76891245-aaf4f580-68ae-11ea-8775-a46300921fc5.png)

Therefore I conclude that this is no longer an issue and should be closed.

**Comment by Cervator** [comment]
Thank you for the detailed research! Much appreciated :-)
